# nom de l'application
spring:
  application:
    name: gestionmembre
  datasource:
    url: jdbc:mysql://mysql:3306/gestionmembre?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: none
logging:
  level:
    org.springframework.web: INFO
eureka:
  client:
    serviceUrl:
      defaultZone: http://registration:9000/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom/html

server:
  port: 8088
