# nom de l'application
spring:
  application:
    name: gestionmembre
  datasource:
    url: jdbc:mysql://localhost:3306/gestionMembre?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    org.springframework.web: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9000/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

server:
  port: 8088
